# Sidebar navigation

- label: 'Demo'
  link: 'https://demo.squzy.app'
- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Products
  items:
    - label: 'Squzy Monitoring'
      link: '/usage/squzy-monitoring'
