# Sidebar navigation

- label: 'Demo'
  link: 'https://demo.squzy.app'
- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Squzy structure
  link: '/squzy-structure'
- label: 'Squzy Proto'
  link: '/squzy-proto'
- label: Products
  items:
    - label: 'Squzy Monitoring'
      link: '/usage/squzy-monitoring'
    - label: 'Squzy Incident'
      link: '/usage/squzy-incident/squzy-incident'
    - label: 'Incident Rules'
      link: '/usage/squzy-incident/incident-rules'
    - label: 'Squzy Storage'
      link: '/usage/squzy-storage/squzy-storage'
    - label: 'Squzy Agent Client'
      link: '/usage/squzy-agent/squzy-agent-client'
    - label: 'Squzy Agent Server'
      link: '/usage/squzy-agent/squzy-agent-server'
